###
GET http://localhost:4000/api/items
###
POST http://localhost:4000/api/items
Content-Type: application/json

{
    "name": "string",
    "price": 9 ,
    "size": "string",
    "color": "string",
    "electric": "string",
    "quantity": 10,
    "space": "string"
}

###
GET http://localhost:4000/api/items/65f9db6dbbae001fcde9dfd5

###
GET http://localhost:4000/api/items/price/9

###
DELETE http://localhost:4000/api/items/65e8a70330df0bc683659e9d1.1 200 OK


###
PUT http://localhost:4000/api/items/65eb05a0a1507754e8238b40/
Content-Type: application/json

{
    "price": 1000000
}

###
GET http://localhost:4000/api/items/65fb3365104c733ce81a88a5

###

GET http://localhost:4000/api/items/color/Rojo
