###
GET http://localhost:4000/api/items
###
POST http://localhost:4000/api/items
Content-Type: application/json

{
    "name": "Bedrix",
    "price": "69",
    "size": "xxxxs",
    "color": "carton",
    "electric": "si"
}

###
GET http://localhost:4000/api/items/65df75e62c5a0cc5544f4d05

###
DELETE http://localhost:4000/api/items/65e8a70330df0bc683659e9d1.1 200 OK


###
PUT http://localhost:4000/api/items/65df75e62c5a0cc5544f4d05/
Content-Type: application/json

{
    "price": 1000000
}